version: "3.8"
services: 
  backend:
    build: ./backend
    ports:
      - "4000:4000"
      - "1234:1234"
    depends_on:
      - db
  
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
