apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: collab-app
spec:
  replicas: 1                       # one backend pod for now
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/ahmoued/collab-backend:latest
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_HOST
          value: postgres          # service name of Postgres
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
