apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: collab-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/ahmoued/collab-frontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: BACKEND_URL
          value: http://backend:4000
