name: CI/CD
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get the code
        uses: actions/checkout@v3

      - name: get node installed
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: install backend dependencies
        run: |
          cd backend
          npm install

      - name: install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: login to ghcr
        run: echo ${{secrets.GHCR_PAT}} | docker login ghcr.io -u ahmoued --password-stdin

      - name: build backend docker image
        run: docker build -t ghcr.io/ahmoued/collab-backend:latest ./backend

      - name: build frontend docker image
        run: docker build -t ghcr.io/ahmoued/collab-frontend:latest ./frontend

      - name: push backend docker image
        run: docker push ghcr.io/ahmoued/collab-backend:latest

      - name: push frontend docker image
        run: docker push ghcr.io/ahmoued/collab-frontend:latest